### ISSUE TITLE
brew set not working from console

### ISSUE THREAD

**Issue by 100petr** [BreweryTeam/BreweryX#16]
If I set the command brew set %player_name% 0 to drink (so it is executed from the console) nothing changes and only this appears in the console.  ![image](https://github.com/user-attachments/assets/b0d7412b-bb5c-4fe9-b642-cc8499c789ae) Of course, I have the placeholder downloaded and I verified the functionality via papi parse. 
I also tried the delay, i.e. / 3s. If I enter the command from the game and with a specific username, the command works. But the command does not work from the console even when specifying a user.
![image](https://github.com/user-attachments/assets/ff6c488a-262b-4c70-b202-217740912a55)
![image](https://github.com/user-attachments/assets/f17f1e0f-8a30-4405-970e-4b5473bf10fa)
![image](https://github.com/user-attachments/assets/0a315d54-7c15-457a-b51f-57dcf78c68c1)
![image](https://github.com/user-attachments/assets/2d171311-0ef8-407a-b615-03f3a7a4a660)
I tried both brew and brewery.
![image](https://github.com/user-attachments/assets/55cec575-70e8-40a9-b441-754c80b56d27)
![image](https://github.com/user-attachments/assets/bd4be1b0-56a6-41d4-aced-ba1ff799ee01)

**Comment by TomLewis** [comment]
May be the same issue as mine from 2021.

https://github.com/DieReicheErethons/Brewery/issues/371

**Comment by TomLewis** [comment]
> The create command was designed as a player command and I therefore can't make it usable for the console, without changing the syntax to accept a player parameter

Can we get another command to spawn from console? then we can ues brewing from any other plugin to make a brew, say for quests.

**Comment by TomLewis** [comment]
Yeah no rush ahah I asked back in 2021 or something, so the fact it's possible is brilliant!
