### ISSUE TITLE
Curing a hangover?

### ISSUE THREAD

**Issue by TomLewis** [BreweryTeam/BreweryX#36]
We found out that hangovers are now a thing! A 7 day hangover is ONE HELL of a hangover LOL idealy it would be better off set in ticks/seconds/mins, as half a day would be closer to real life!

But, players have been asking how to cure this hangover! Is there a way they can brew a brew or eat something in-game to speed up this hangover they get?

Could we also get an admin command to wipe a hangover from players?

**Comment by Vutka1** [comment]
Hangover? You mean the negative status effect after you log out while drunk? They can be cleared with bucket of milk, can't they?

**Comment by TomLewis** [comment]
@Vutka1 no, I mean Hangover, as stated. It was added to BrewingX when moved from Brewing, look at the config for "Hangover" specifically that word.

**Comment by Vutka1** [comment]
> @Vutka1 no, I mean Hangover, as stated. 

This is pretty much what I described: if you log out while drunk, on login you'll have, like, mining fatigue and slowness. And you can cure that with a milk bucket, since this is what you initially asked about.

**Comment by Vutka1** [comment]
@TomLewis anything else? Can I close this?
