### ISSUE TITLE
Star on item lore was not replace correctly when seal

### ISSUE THREAD

**Issue by Barlaf** [BreweryTeam/BreweryX#42]
Hello ! 
When i seal any brew, the item lore was not update correctly and adding a new line return
## Version
I update from 3.2.8 to 3.3.2
```
[17:18:21 INFO]: BreweryX version 3.3.2
[17:18:21 INFO]: Website: https://www.spigotmc.org/resources/breweryx.114777/
[17:18:21 INFO]: Authors: Jsinco, Mitality, Szarkans, Sn0wStorm, TTTheKing and Grafe
```
### Before seal
![image](https://github.com/user-attachments/assets/de07a4fd-ed0d-4baf-933c-0f18595b2cd0)
![image](https://github.com/user-attachments/assets/dee485be-5968-403e-ac96-22f648ffe7da)
### After seal
![image](https://github.com/user-attachments/assets/320a0ef7-b67e-45dc-acfa-a91b17fc41d8)
![image](https://github.com/user-attachments/assets/23962ce4-d808-41be-9952-6e2dfc734290)

**Comment by Jsinco** [comment]
lore issues should be resolved in the latest version
