### ISSUE TITLE
Wakeup function not working 

### ISSUE THREAD

**Issue by KoCitrusMaker** [BreweryTeam/BreweryX#57]
The Wakup function isn't working on my server. 

I've gotten the drunkeness level high several times and logged off on a very high percentage and the function hasn't taken me to the 20+ places I've added to the wakeup add command, is there a possibility I'm miss configuring this or its maybe the fact that it's an aternos server? 

I've checked the docs and configure several times sure it's set to true. 

Thanks in advanced!

**Comment by Vutka1** [comment]
Were you an operator when doing this? OPs (or anyone with `brewery.*` permission) are not affected by wakeup points mechanic

**Comment by KoCitrusMaker** [comment]
That explains. Yes, I am.
Is there any way to change this?

**Comment by Vutka1** [comment]
> That explains. Yes, I am. Is there any way to change this?

If you're testing your wakeup points, try this:
1) deop yourself
2) instead give yourself `brewery.mod` or `brewery.admin` permission (they give you access to commands but do not have wakeup mechanic bypass)

Also, please send your breweryX and minecraft versions. I've just tried myself and it didn't work even without OP, so that might be a bug.

**Comment by KoCitrusMaker** [comment]
The server is paper 1.21.1 while the plugin is v3.5.5 (latest, updated today), I am currently running the test, might need some time until I send back the results, 2 hours give or take

**Comment by KoCitrusMaker** [comment]
Finished testing, got in and out of the server a total of 3 times in the span of 2 hours, none of the times i was teleported to the wake points, I de-op'ed and gave myself the necessary permissions (brew.admin) with luckperms

**Comment by Jsinco** [comment]
This *should* have been fixed in BreweryX v3.4.0, any issues still present with this?

**Comment by KoCitrusMaker** [comment]
Issue still present, something even weirder happened with this same thing:

I left an alt account afk in my server for 10 minutes to prevent the server from closing and turning off (it's aternos) and i log out of the server on the main account with more than half drunkness, i come back after the 10 minutes have passed and i find myself in the same spot i logged off and no longer drunk

**Comment by Vutka1** [comment]
> I log out of the main account with more than half drunkness, i come back after the 10 minutes have passed and i find myself _[...]_ no longer drunk.

This is normal, you drunkenness can go down while you're offline, it's a normal behaviour. Also hangover (negative effect) might apply, if you were 100% drunk while logging off.
Though it might be strange how it took only 10 minutes for your drunkenness to disappear (not sure)

**Comment by KoCitrusMaker** [comment]
Repeated same scenario, the drunkness did lower but didin't disappear completely this time, while still, wakeup function is still not working. I am more than willing to share luckperms files and even server ip to show the issue

**Comment by Vutka1** [comment]
Wakeups supposedly have been fixed in 3.4.3, @KoCitrusMaker do you still have any issues with them?

**Comment by KoCitrusMaker** [comment]
![image](https://github.com/user-attachments/assets/e5a47458-b3b0-40cd-b0fd-af5326335f78)

The issue has been fixed completely (tested on latest, 3.4.5), thank you so much!
